# Generated by Django 5.2.3 on 2025-10-01 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default="Cote d'ivoire", max_length=100, verbose_name='Pays')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('issue_type', models.CharField(choices=[('SCREEN', 'Écran cassé'), ('BATTERY', 'Problème de batterie'), ('CHARGE', 'Problème de charge'), ('SOFTWARE', 'Problème logiciel'), ('WATER', 'Dégât des eaux'), ('OTHER', 'Autre')], max_length=20, verbose_name='Type de panne')),
                ('device_model', models.CharField(max_length=100, verbose_name="Modèle de l'appareil")),
                ('description', models.TextField(verbose_name='Description de la panne')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Demande de réparation',
                'verbose_name_plural': 'Demandes de réparation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Clé de session')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('product_type', models.CharField(choices=[('SHEET', 'Draps'), ('PHONE', 'Téléphone')], max_length=10, verbose_name='Type de produit')),
                ('sheet_size', models.CharField(blank=True, choices=[('SIMPLE', 'Simple (90x190cm)'), ('DOUBLE', 'Double (140x190cm)'), ('QUEEN', 'Queen (160x200cm)'), ('KING', 'King (180x200cm)')], max_length=10, null=True, verbose_name='Taille')),
                ('color', models.CharField(blank=True, choices=[('WHITE', 'Blanc'), ('GRAY', 'Gris'), ('BLUE', 'Bleu'), ('PINK', 'Rose'), ('GREEN', 'Vert'), ('BEIGE', 'Beige')], max_length=10, null=True, verbose_name='Couleur')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Matière')),
                ('phone_brand', models.CharField(blank=True, choices=[('TECHGIANT', 'TechGiant'), ('GALAXY', 'Galaxy'), ('PIXEL', 'Pixel'), ('ONEPLUS', 'OnePlus'), ('XIAOMI', 'Xiaomi'), ('APPLE', 'Apple')], max_length=20, null=True, verbose_name='Marque')),
                ('phone_category', models.CharField(blank=True, choices=[('BESTSELLER', 'Meilleures ventes'), ('OFFER', 'Offres spéciales'), ('REFURBISHED', 'Reconditionnés'), ('ACCESSORY', 'Accessoires')], max_length=20, null=True, verbose_name='Catégorie téléphone')),
                ('storage', models.CharField(blank=True, max_length=50, verbose_name='Stockage')),
                ('screen_size', models.CharField(blank=True, max_length=50, verbose_name='Taille écran')),
                ('processor', models.CharField(blank=True, max_length=100, verbose_name='Processeur')),
                ('camera', models.CharField(blank=True, max_length=200, verbose_name='Appareil photo')),
                ('battery', models.CharField(blank=True, max_length=50, verbose_name='Batterie')),
                ('operating_system', models.CharField(blank=True, max_length=50, verbose_name="Système d'exploitation")),
                ('ram', models.CharField(blank=True, max_length=50, verbose_name='Mémoire RAM')),
                ('connectivity', models.CharField(blank=True, max_length=200, verbose_name='Connectivité')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('on_sale', models.BooleanField(default=False, verbose_name='En promotion')),
                ('discount_percentage', models.IntegerField(default=0, verbose_name='Pourcentage de réduction')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='commande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='Panier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article du panier',
                'verbose_name_plural': 'Articles du panier',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
