# Generated by Django 5.2.3 on 2025-10-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Paiement à la livraison'), ('WAVE', 'Wave'), ('ORANGE', 'Orange Money'), ('MTN', 'MTN Money'), ('PAYDUNYA', 'PayDunya Checkout')], default='CASH', max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence paiement'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué'), ('CASH_ON_DELIVERY', 'À payer à la livraison')], default='PENDING', max_length=20, verbose_name='Statut paiement'),
        ),
    ]
