# Generated by Django 5.2.3 on 2025-10-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_payment_method_order_payment_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='decoration_type',
            field=models.CharField(blank=True, choices=[('SHEET', 'Draps'), ('CURTAIN', 'Rideaux'), ('CARPET', 'Tapis'), ('OTHER', 'Autre décoration')], max_length=20, null=True, verbose_name='Type de décoration'),
        ),
        migrations.AddField(
            model_name='product',
            name='needs_custom_quote',
            field=models.BooleanField(default=False, verbose_name='Nécessite un devis personnalisé'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix au m² (pour tapis)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SHEET', 'Draps'), ('PHONE', 'Téléphone'), ('DECORATION', 'Déco & Aménagement')], max_length=10, verbose_name='Type de produit'),
        ),
        migrations.CreateModel(
            name='CustomQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('address', models.TextField(verbose_name='Adresse de visite')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('preferred_date', models.DateField(verbose_name='Date préférée')),
                ('preferred_time', models.CharField(choices=[('MORNING', 'Matin (8h-12h)'), ('AFTERNOON', 'Après-midi (14h-18h)'), ('EVENING', 'Soir (18h-20h)')], max_length=20, verbose_name='Plage horaire préférée')),
                ('room_dimensions', models.CharField(blank=True, max_length=100, verbose_name='Dimensions de la pièce')),
                ('window_measurements', models.CharField(blank=True, max_length=100, verbose_name='Mesures des fenêtres (pour rideaux)')),
                ('bed_size', models.CharField(blank=True, max_length=50, verbose_name='Taille du lit (pour draps)')),
                ('special_requests', models.TextField(blank=True, verbose_name='Demandes spéciales')),
                ('fabric_preference', models.CharField(blank=True, max_length=100, verbose_name='Préférence de tissu')),
                ('color_preferences', models.CharField(blank=True, max_length=200, verbose_name='Préférences de couleurs')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONTACTED', 'Client contacté'), ('SCHEDULED', 'Rendez-vous planifié'), ('QUOTED', 'Devis envoyé'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix devisé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Demande de devis personnalisé',
                'verbose_name_plural': 'Demandes de devis personnalisés',
                'ordering': ['-created_at'],
            },
        ),
    ]
