# Generated by Django 5.2.3 on 2025-10-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_decoration_type_product_needs_custom_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PHONE', 'Téléphone'), ('DECORATION', 'Déco & Aménagement')], max_length=10, verbose_name='Type de produit'),
        ),
    ]
