# Generated by Django 5.2.3 on 2025-10-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='battery',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Batterie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='camera',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Appareil photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='connectivity',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Connectivité'),
        ),
        migrations.AlterField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Processeur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mémoire RAM'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Taille écran'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stockage'),
        ),
    ]
