# Generated by Django 5.2.3 on 2025-10-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_battery_alter_product_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Système d'exploitation"),
        ),
    ]
