# Generated by Django 5.2.3 on 2025-10-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_operating_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', 'Blanc'), ('GRAY', 'Gris'), ('BLUE', 'Bleu'), ('PINK', 'Rose'), ('GREEN', 'Vert'), ('BEIGE', 'Beige'), ('BLACK', 'Noir')], max_length=10, null=True, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='product',
            name='phone_brand',
            field=models.CharField(blank=True, choices=[('APPLE', 'Apple'), ('SAMSUNG', 'Samsung'), ('ITEL', 'Itel'), ('TECHNO', 'Techno'), ('HUAWEI', 'Huawei'), ('INFINIX', 'Infinix')], max_length=20, null=True, verbose_name='Marque'),
        ),
    ]
