# Generated by Django 5.2.3 on 2025-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_color_alter_product_phone_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='phone_brand',
            field=models.CharField(blank=True, choices=[('APPLE', 'Apple'), ('SAMSUNG', 'Samsung'), ('ITEL', 'Itel'), ('TECHNO', 'Techno'), ('HUAWEI', 'Huawei'), ('INFINIX', 'Infinix'), ('XIAOMI', 'Xiaomi'), ('PIXEL', 'Pixel')], max_length=20, null=True, verbose_name='Marque'),
        ),
    ]
