# Generated by Django 5.2.3 on 2025-11-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='electronics_category',
            field=models.CharField(blank=True, choices=[('SMARTPHONE', 'Smartphones'), ('TABLET', 'Tablettes'), ('HEADPHONE', 'Casques audio'), ('CHARGER', 'Chargeurs & Câbles'), ('SMARTWATCH', 'Montres connectées'), ('EARBUDS', 'Écouteurs'), ('POWERBANK', 'Power banks'), ('PHONE_CASE', 'Coques & Protection'), ('REFURBISHED', 'Reconditionnés'), ('OTHER_ACCESSORY', 'Autres accessoires')], max_length=20, null=True, verbose_name='Catégorie électronique'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('ELECTRONICS', 'Électronique & Accessoires'), ('DECORATION', 'Déco & Aménagement')], max_length=15, verbose_name='Type de produit'),
        ),
    ]
