# Generated by Django 5.2.3 on 2025-11-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='winipayer_payment_url',
            field=models.URLField(blank=True, verbose_name='URL de paiement Winipayer'),
        ),
        migrations.AddField(
            model_name='order',
            name='winipayer_transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Transaction Winipayer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Paiement à la livraison'), ('WAVE', 'Wave'), ('ORANGE', 'Orange Money'), ('MTN', 'MTN Money'), ('CARD', 'Carte Bancaire')], default='CASH', max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('INITIATED', 'Paiement initié'), ('PAID', 'Payé'), ('FAILED', 'Échoué'), ('CASH_ON_DELIVERY', 'À payer à la livraison')], default='PENDING', max_length=20, verbose_name='Statut paiement'),
        ),
    ]
