# Generated by Django 5.2.3 on 2025-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_winipayer_payment_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Paiement à la livraison'), ('ONLINE', 'Paiement en ligne')], default='CASH', max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
