# Generated by Django 5.2.3 on 2025-11-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'En attente de paiement'), ('PENDING', 'En attente'), ('INITIATED', 'Paiement initié'), ('PAID', 'Payé'), ('FAILED', 'Échoué'), ('CASH_ON_DELIVERY', 'À payer à la livraison')], default='PENDING', max_length=20, verbose_name='Statut paiement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'En attente de paiement'), ('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
    ]
