"""
Django settings for ecommerce_project project.

Generated by 'django-admin startproject' using Django 5.2.3.
"""

# settings.py - VERSION RENDER
from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-key-for-render')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Hosts pour Render
ALLOWED_HOSTS = [
    'dsd-general-trading.onrender.com',
    'dsd-general-trading.com',
    'www.dsd-general-trading.com',
    'localhost',
    '127.0.0.1',
]

# CSRF pour Render
CSRF_TRUSTED_ORIGINS = [
    'https://dsd-general-trading.onrender.com',
    'https://dsd-general-trading.com',
    'https://www.dsd-general-trading.com',
]

# --- APPLICATIONS ---
INSTALLED_APPS = [
    'cloudinary_storage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'shop',
    'users',
]

# --- MIDDLEWARE ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shop.middleware.NotificationMiddleware',
    'shop.middleware.AdminSecurityMiddleware',
]

ROOT_URLCONF = 'ecommerce_project.urls'

# --- TEMPLATES ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart_context',
                'shop.context_processors.admin_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce_project.wsgi.application'

# --- DATABASE ---
# Render fournit DATABASE_URL automatiquement
if 'RENDER' in os.environ or 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# --- CLOUDINARY CONFIGURATION ---
import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME'),
    api_key=os.environ.get('CLOUDINARY_API_KEY'),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET'),
    secure=True
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# --- STATIC FILES ---
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'shop/static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise pour les statiques
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- MEDIA (géré par Cloudinary) ---
MEDIA_URL = '/media/'

# ... Le reste de votre configuration existante (CinetPay, etc.)
# --- DEFAULT PK ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CINETPAY CONFIG ---
CINETPAY_API_KEY = os.environ.get('CINETPAY_API_KEY', '')
CINETPAY_SITE_ID = os.environ.get('CINETPAY_SITE_ID', '')
CINETPAY_MODE = os.environ.get('CINETPAY_MODE', 'test')

if CINETPAY_MODE == 'prod':
    CINETPAY_BASE_URL = "https://api.cinetpay.com/v1"
    CINETPAY_CHECKOUT_URL = "https://secure.cinetpay.com"
else:
    CINETPAY_BASE_URL = "https://api-checkout.cinetpay.com/v1"
    CINETPAY_CHECKOUT_URL = "https://secure-checkout.cinetpay.com"