"""
Django settings for ecommerce_project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-prct4r0m&#@h#i0vnm=z(8sx)!)@*a&2rc+cr6kq1us7tzr5%6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    'dsd-general-trading.com',
    'www.dsd-general-trading.com',
    'localhost',
    '127.0.0.1',
    '.up.railway.app',
    'ecommerceproject-production-c284.up.railway.app',
]
CSRF_TRUSTED_ORIGINS = ['https://dsd-general-trading.com', 'https://www.dsd-general-trading.com']

# Application definition

INSTALLED_APPS = [
    'cloudinary_storage',  # DOIT ÊTRE EN PREMIER
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',          # APRÈS cloudinary_storage
    'shop',  # Notre app boutique
    'users', # Notre app utilisateurs
]

# Configuration Cloudinary - PRODUCTION ONLY
if not DEBUG:
    import cloudinary
    import cloudinary.uploader
    import cloudinary.api

    # Vérifiez d'abord si les variables existent
    cloud_name = os.environ.get('CLOUDINARY_CLOUD_NAME')
    api_key = os.environ.get('CLOUDINARY_API_KEY')
    api_secret = os.environ.get('CLOUDINARY_API_SECRET')

    if cloud_name and api_key and api_secret:
        cloudinary.config(
            cloud_name=cloud_name,
            api_key=api_key,
            api_secret=api_secret,
            secure=True
        )
        DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
        print("=== CLOUDINARY ACTIVÉ EN PRODUCTION ===")
        print(f"Cloud Name: {cloud_name}")
        print(f"API Key présent: {bool(api_key)}")
        print(f"API Secret présent: {bool(api_secret)}")
    else:
        print("=== VARIABLES CLOUDINARY MANQUANTES ===")
        print(f"Cloud Name: {cloud_name}")
        print(f"API Key: {api_key}")
        print(f"API Secret: {api_secret}")
else:
    # En développement, utilisez le stockage local
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
    MEDIA_URL = '/media/'
    print("=== STOCKAGE LOCAL (DÉVELOPPEMENT) ===")

# Configuration des médias (utilisée dans les deux cas)
MEDIA_URL = '/media/'

LOGIN_URL ='/gestion-securisee/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shop.middleware.NotificationMiddleware',
    'shop.middleware.AdminSecurityMiddleware'
]

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'ecommerce_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart_context',
                'shop.context_processors.admin_notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# En développement
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'shop/static'),
]

# En production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration PayDunya (Wave, Orange, MTN)
# Charge les variables d'environnement

# Configuration PayDunya
CINETPAY_API_KEY = os.environ.get('CINETPAY_API_KEY', '')
CINETPAY_SITE_ID = os.environ.get('CINETPAY_SITE_ID', '')
CINETPAY_MODE = os.environ.get('CINETPAY_MODE', 'test')

# URLs CinetPay
if CINETPAY_MODE == 'prod':
    CINETPAY_BASE_URL = "https://api.cinetpay.com/v1"
    CINETPAY_CHECKOUT_URL = "https://secure.cinetpay.com"
else:
    CINETPAY_BASE_URL = "https://api-checkout.cinetpay.com/v1"
    CINETPAY_CHECKOUT_URL = "https://secure-checkout.cinetpay.com"